id: A51BEA5EE
title: 'The Chariot Bound for Sukhāvatī, the Blissful Realm: The Liturgy for Cultivating
  Buddha Amitābha’s Pure Realm'
type: translation
pechas:
- I57EE7EB4
- IC4737CEC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:33:56.499144
  last_modified_at: 2023-01-04 11:33:56.499158
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I57EE7EB4/8832: D3CF
  IC4737CEC/A965: D3CF
